/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SocialLink = {
  _type: 'socialLink';
  name: string;
  link: string;
  iconName: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?:
        | 'normal'
        | 'h1'
        | 'h2'
        | 'h3'
        | 'h4'
        | 'h5'
        | 'h6'
        | 'blockquote'
        | 'unstyled';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }
>;

export type Configuration = {
  _id: string;
  _type: 'configuration';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  showOriginalSourceLink: boolean;
  mailInfo?: {
    from?: string;
    to?: string;
  };
  PageSetup: {
    showCareerLink: boolean;
    showCertificateLink: boolean;
    showContactLink: boolean;
    showProjectLink: boolean;
  };
};

export type Career = {
  _id: string;
  _type: 'career';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  careerHide: boolean;
  employmentType:
    | 'Contract'
    | 'Self-employed'
    | 'Part-time'
    | 'Full-time'
    | 'Internship'
    | 'Apprenticeship'
    | 'Freelance';
  title: string;
  name: string;
  location?: string;
  locationType: 'On-site' | 'Hybrid' | 'Remote';
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  startDate: string;
  endDate?: string;
  description: BlockContent;
  skillTags?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  githubUrl?: string;
  githubImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type ContactForms = {
  _id: string;
  _type: 'contactForms';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  message?: string;
  reviewed?: boolean;
};

export type Certificate = {
  _id: string;
  _type: 'certificate';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  certificateHide: boolean;
  idx: string;
  name: string;
  authorityName: string;
  authorityImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  startDate: string;
  endDate?: string;
  certificateLink?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projectHide: boolean;
  name: string;
  slug: Slug;
  body: BlockContent;
  projectUrl?: UrlWrapper;
  sourceUrl?: UrlWrapper;
  projectIssuer?: IssuerWrapper;
  externalAuthors?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'author';
  }>;
  projectImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  projectImages: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  categories?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  profileStatus: 'completed' | 'ongoing' | 'abandoned';
};

export type IssuerWrapper = {
  _type: 'issuerWrapper';
  name?: string;
  link?: string;
};

export type UrlWrapper = {
  _type: 'urlWrapper';
  url: string;
  visibility?: boolean;
};

export type PersonalInfo = {
  _id: string;
  _type: 'personalInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  title: string;
  jobVisibility: boolean;
  jobStatus: 'open' | 'inbetween' | 'close';
  CV?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    _type: 'file';
  };
  CVLastUpdatedAt?: string;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  bio: BlockContent;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  skillTags?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};
export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ./src/groq/queries.ts
// Variable: ProfileDetails
// Query:   *[_type == "personalInfo"] | order(_createdAt desc) {    ...,    "skills": skillTags[]->  }[0]
export type ProfileDetailsResult = {
  _id: string;
  _type: 'personalInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  title: string;
  jobVisibility: boolean;
  jobStatus: 'close' | 'inbetween' | 'open';
  CV?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    _type: 'file';
  };
  CVLastUpdatedAt?: string;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  bio: BlockContent;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  skillTags?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  skills: Array<{
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
  }> | null;
} | null;
// Variable: AllSocialLinks
// Query:   coalesce(*[_type == "personalInfo"] | order(_updatedAt desc) [0].socialLinks, [])
export type AllSocialLinksResult =
  | Array<
      {
        _key: string;
      } & SocialLink
    >
  | Array<never>;
// Variable: AllCertificates
// Query:   *[_type == "certificate" && certificateHide == false] | order(startDate desc)
export type AllCertificatesResult = Array<{
  _id: string;
  _type: 'certificate';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  certificateHide: boolean;
  idx: string;
  name: string;
  authorityName: string;
  authorityImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  startDate: string;
  endDate?: string;
  certificateLink?: string;
}>;
// Variable: AllProjectDetails
// Query:   *[_type == "project" && projectHide == false] | order(_updatedAt desc) {    ...,    "tags": categories[]->  }
export type AllProjectDetailsResult = Array<{
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projectHide: boolean;
  name: string;
  slug: Slug;
  body: BlockContent;
  projectUrl?: UrlWrapper;
  sourceUrl?: UrlWrapper;
  projectIssuer?: IssuerWrapper;
  externalAuthors?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'author';
  }>;
  projectImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  projectImages: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  categories?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  profileStatus: 'abandoned' | 'completed' | 'ongoing';
  tags: Array<{
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
  }> | null;
}>;
// Variable: AllCareers
// Query:   *[_type == "career" && careerHide == false] | order(startDate desc) {    ...,    "tags": skillTags[]->  }
export type AllCareersResult = Array<{
  _id: string;
  _type: 'career';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  careerHide: boolean;
  employmentType:
    | 'Apprenticeship'
    | 'Contract'
    | 'Freelance'
    | 'Full-time'
    | 'Internship'
    | 'Part-time'
    | 'Self-employed';
  title: string;
  name: string;
  location?: string;
  locationType: 'Hybrid' | 'On-site' | 'Remote';
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  startDate: string;
  endDate?: string;
  description: BlockContent;
  skillTags?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  tags: Array<{
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
  }> | null;
}>;
// Variable: ProjectConfig
// Query:   *[_type == "configuration"] | order(_updatedAt desc) [0]
export type ProjectConfigResult = {
  _id: string;
  _type: 'configuration';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  showOriginalSourceLink: boolean;
  mailInfo?: {
    from?: string;
    to?: string;
  };
  PageSetup: {
    showCareerLink: boolean;
    showCertificateLink: boolean;
    showContactLink: boolean;
    showProjectLink: boolean;
  };
} | null;
// Variable: ProjectConfigName
// Query:   *[_type == "configuration"] | order(_updatedAt desc) [0].name
export type ProjectConfigNameResult = string | null;
// Variable: ProjectInfoName
// Query:   *[_type == "personalInfo"] | order(_updatedAt desc) [0].name
export type ProjectInfoNameResult = string | null;
// Variable: CVReference
// Query:   *[_type == "personalInfo"] | order(_updatedAt desc) [0].CV.asset._ref
export type CVReferenceResult = string | null;
