import React from 'react';
import Head from 'next/head';

interface T {
  title?: string;
  description?: string;
  icon?: string;
}
const MetaHead: React.FC<T> = ({ title, description, icon }) => {
  return (
    <Head>
      <title>{title || `Obi Fortune Personal Portfolio`}</title>
      <meta
        name="description"
        content={description || `Generated by create next app`}
      />
      <link rel="icon" href={icon || `/favicon.ico`} />
      <link
        rel="stylesheet"
        href="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.min.css"
      />
    </Head>
  );
};

export default MetaHead;
